# Generated by Django 5.2.4 on 2025-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='descripcion',
            field=models.CharField(default='sin descripción'),
            preserve_default=False,
        ),
    ]
