# Generated by Django 5.2.4 on 2025-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_director_movie_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='descripcion',
            field=models.CharField(default='sin descripción', max_length=255),
        ),
    ]
